# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: ./Docker
      dockerfile: app.Dockerfile
    ports:
      - "4000:4000"
      - "9229:9229"
    environment:
      DB_HOST: 'database'
      DB_PORT: 5432
      DB_DATABASE: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'password'
    depends_on:
      - postgres
    networks:
      - app_net
 
  postgres:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    networks:
      - app_net
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: 'password'
  
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.238.0/24