version: "3.7"
services:
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - postgres

  postgres:
    build: 
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  